/** Generated by scripts/build-npc-manifest.mjs — do not edit by hand. */

import type { BilingualText } from '../types/route'

export type NpcAudioFilter = 'all' | string

export interface NpcAudioItem {
  id: string
  category: string
  number: number
  title: BilingualText
  detail: BilingualText
  audioUrl: string | null
  /** No licensed clip yet — show placeholder only */
  unavailable?: boolean
}

export const NPC_CATEGORIES: readonly string[] = [
  "行车抱怨",
  "下车抱怨",
  "服务抱怨",
  "打招呼，感谢",
  "Hello",
  "Bye",
  "Angry",
  "Complaint",
  "ComplaintSerious",
  "StopSkipped",
  "Wrong",
  "FareWrong",
  "DoorOpened",
  "DoorClosed",
  "Camera",
  "Cold",
  "Hot",
  "NoKneel",
]

export const NPC_CATEGORY_TEXTS: Readonly<Record<string, BilingualText>> = {
  "行车抱怨": { zh: "行车", en: "Driving" },
  "下车抱怨": { zh: "下车", en: "Alighting" },
  "服务抱怨": { zh: "服务", en: "Service" },
  "打招呼，感谢": { zh: "感谢", en: "Thanks" },
  "Hello": { zh: "打招呼", en: "Hello" },
  "Bye": { zh: "告别", en: "Bye" },
  "Angry": { zh: "愤怒", en: "Angry" },
  "Complaint": { zh: "抱怨", en: "Complaint" },
  "ComplaintSerious": { zh: "严重抱怨", en: "Serious complaint" },
  "StopSkipped": { zh: "跳站", en: "Stop skipped" },
  "Wrong": { zh: "乘错车", en: "Wrong route" },
  "FareWrong": { zh: "车费错误", en: "Wrong fare" },
  "DoorOpened": { zh: "车门打开", en: "Door opened" },
  "DoorClosed": { zh: "车门关闭", en: "Door closed" },
  "Camera": { zh: "相机", en: "Camera" },
  "Cold": { zh: "寒冷", en: "Cold" },
  "Hot": { zh: "炎热", en: "Hot" },
  "NoKneel": { zh: "请勿跪坐", en: "No kneeling" },
}

export const npcAudioItems: readonly NpcAudioItem[] = [
  { id: "npc-Hello-1", category: "Hello", number: 1, title: { zh: "Balloon Boy Hi", en: "Balloon Boy Hi" }, detail: { zh: "打招呼", en: "Hello" }, audioUrl: "./audio/npc/Hello/Balloon%20Boy%20Hi.ogg", },
  { id: "npc-Hello-2", category: "Hello", number: 2, title: { zh: "echo3b", en: "echo3b" }, detail: { zh: "打招呼", en: "Hello" }, audioUrl: "./audio/npc/Hello/echo3b.ogg", },
  { id: "npc-Hello-3", category: "Hello", number: 3, title: { zh: "hello!", en: "hello!" }, detail: { zh: "打招呼", en: "Hello" }, audioUrl: "./audio/npc/Hello/hello!.ogg", },
  { id: "npc-Hello-4", category: "Hello", number: 4, title: { zh: "hello", en: "hello" }, detail: { zh: "打招呼", en: "Hello" }, audioUrl: "./audio/npc/Hello/hello.ogg", },
  { id: "npc-Hello-5", category: "Hello", number: 5, title: { zh: "Hi how are ya sound effect", en: "Hi how are ya sound effect" }, detail: { zh: "打招呼", en: "Hello" }, audioUrl: "./audio/npc/Hello/Hi%20how%20are%20ya%20sound%20effect.ogg", },
  { id: "npc-Hello-6", category: "Hello", number: 6, title: { zh: "hi", en: "hi" }, detail: { zh: "打招呼", en: "Hello" }, audioUrl: "./audio/npc/Hello/hi.ogg", },
  { id: "npc-Hello-7", category: "Hello", number: 7, title: { zh: "Mine turtle Hello!", en: "Mine turtle Hello!" }, detail: { zh: "打招呼", en: "Hello" }, audioUrl: "./audio/npc/Hello/Mine%20turtle_Hello!.ogg", },
  { id: "npc-Bye-1", category: "Bye", number: 1, title: { zh: "Luigi   Bye Bye (Louder)", en: "Luigi   Bye Bye (Louder)" }, detail: { zh: "告别", en: "Bye" }, audioUrl: "./audio/npc/Bye/Luigi%20-%20Bye-Bye%20(Louder).ogg", },
  { id: "npc-Bye-2", category: "Bye", number: 2, title: { zh: "Thank You", en: "Thank You" }, detail: { zh: "告别", en: "Bye" }, audioUrl: "./audio/npc/Bye/Thank%20You.ogg", },
  { id: "npc-Bye-3", category: "Bye", number: 3, title: { zh: "THANK YOU", en: "THANK YOU" }, detail: { zh: "告别", en: "Bye" }, audioUrl: "./audio/npc/Bye/THANK-YOU.ogg", },
  { id: "npc-Angry-1", category: "Angry", number: 1, title: { zh: "Angry Sound Effect", en: "Angry Sound Effect" }, detail: { zh: "愤怒", en: "Angry" }, audioUrl: "./audio/npc/Angry/Angry%20Sound%20Effect.ogg", },
  { id: "npc-Angry-2", category: "Angry", number: 2, title: { zh: "heavy long scream", en: "heavy long scream" }, detail: { zh: "愤怒", en: "Angry" }, audioUrl: "./audio/npc/Angry/heavy%20long%20scream.ogg", },
  { id: "npc-Complaint-1", category: "Complaint", number: 1, title: { zh: "GLaDOS saying What are you doing", en: "GLaDOS saying What are you doing" }, detail: { zh: "抱怨", en: "Complaint" }, audioUrl: "./audio/npc/Complaint/GLaDOS%20saying%20What%20are%20you%20doing.ogg", },
  { id: "npc-Complaint-2", category: "Complaint", number: 2, title: { zh: "i am reporting you", en: "i am reporting you" }, detail: { zh: "抱怨", en: "Complaint" }, audioUrl: "./audio/npc/Complaint/i%20am%20reporting%20you.ogg", },
  { id: "npc-Complaint-3", category: "Complaint", number: 3, title: { zh: "oh my god", en: "oh my god" }, detail: { zh: "抱怨", en: "Complaint" }, audioUrl: "./audio/npc/Complaint/oh%20my%20god.ogg", },
  { id: "npc-Complaint-4", category: "Complaint", number: 4, title: { zh: "stop right here", en: "stop right here" }, detail: { zh: "抱怨", en: "Complaint" }, audioUrl: "./audio/npc/Complaint/stop%20right%20here.ogg", },
  { id: "npc-Complaint-5", category: "Complaint", number: 5, title: { zh: "why did u do this to me", en: "why did u do this to me" }, detail: { zh: "抱怨", en: "Complaint" }, audioUrl: "./audio/npc/Complaint/why%20did%20u%20do%20this%20to%20me.ogg", },
  { id: "npc-ComplaintSerious-1", category: "ComplaintSerious", number: 1, title: { zh: "Female Scream1", en: "Female Scream1" }, detail: { zh: "严重抱怨", en: "Serious complaint" }, audioUrl: "./audio/npc/ComplaintSerious/Female_Scream1.ogg", },
  { id: "npc-ComplaintSerious-2", category: "ComplaintSerious", number: 2, title: { zh: "GLaDOS saying What are you doing", en: "GLaDOS saying What are you doing" }, detail: { zh: "严重抱怨", en: "Serious complaint" }, audioUrl: "./audio/npc/ComplaintSerious/GLaDOS%20saying%20What%20are%20you%20doing.ogg", },
  { id: "npc-ComplaintSerious-3", category: "ComplaintSerious", number: 3, title: { zh: "MAN DOWN MAN DOWN", en: "MAN DOWN MAN DOWN" }, detail: { zh: "严重抱怨", en: "Serious complaint" }, audioUrl: "./audio/npc/ComplaintSerious/MAN%20DOWN%20MAN%20DOWN.ogg", },
  { id: "npc-ComplaintSerious-4", category: "ComplaintSerious", number: 4, title: { zh: "oh my god", en: "oh my god" }, detail: { zh: "严重抱怨", en: "Serious complaint" }, audioUrl: "./audio/npc/ComplaintSerious/oh%20my%20god.ogg", },
  { id: "npc-ComplaintSerious-5", category: "ComplaintSerious", number: 5, title: { zh: "Sound Effect! Man Screaming", en: "Sound Effect! Man Screaming" }, detail: { zh: "严重抱怨", en: "Serious complaint" }, audioUrl: "./audio/npc/ComplaintSerious/Sound%20Effect!%20Man%20Screaming.ogg", },
  { id: "npc-ComplaintSerious-6", category: "ComplaintSerious", number: 6, title: { zh: "stop right here", en: "stop right here" }, detail: { zh: "严重抱怨", en: "Serious complaint" }, audioUrl: "./audio/npc/ComplaintSerious/stop%20right%20here.ogg", },
  { id: "npc-ComplaintSerious-7", category: "ComplaintSerious", number: 7, title: { zh: "TF2   Engineer Death 3", en: "TF2   Engineer Death 3" }, detail: { zh: "严重抱怨", en: "Serious complaint" }, audioUrl: "./audio/npc/ComplaintSerious/TF2%20-%20Engineer%20Death%203.ogg", },
  { id: "npc-ComplaintSerious-8", category: "ComplaintSerious", number: 8, title: { zh: "why did u do this to me", en: "why did u do this to me" }, detail: { zh: "严重抱怨", en: "Serious complaint" }, audioUrl: "./audio/npc/ComplaintSerious/why%20did%20u%20do%20this%20to%20me.ogg", },
  { id: "npc-StopSkipped-1", category: "StopSkipped", number: 1, title: { zh: "flying lesson", en: "flying lesson" }, detail: { zh: "跳站", en: "Stop skipped" }, audioUrl: "./audio/npc/StopSkipped/flying%20lesson.ogg", },
  { id: "npc-StopSkipped-2", category: "StopSkipped", number: 2, title: { zh: "GLaDOS saying What are you doing", en: "GLaDOS saying What are you doing" }, detail: { zh: "跳站", en: "Stop skipped" }, audioUrl: "./audio/npc/StopSkipped/GLaDOS%20saying%20What%20are%20you%20doing.ogg", },
  { id: "npc-StopSkipped-3", category: "StopSkipped", number: 3, title: { zh: "i am late now", en: "i am late now" }, detail: { zh: "跳站", en: "Stop skipped" }, audioUrl: "./audio/npc/StopSkipped/i%20am%20late%20now.ogg", },
  { id: "npc-StopSkipped-4", category: "StopSkipped", number: 4, title: { zh: "i am reporting you", en: "i am reporting you" }, detail: { zh: "跳站", en: "Stop skipped" }, audioUrl: "./audio/npc/StopSkipped/i%20am%20reporting%20you.ogg", },
  { id: "npc-StopSkipped-5", category: "StopSkipped", number: 5, title: { zh: "stop right here", en: "stop right here" }, detail: { zh: "跳站", en: "Stop skipped" }, audioUrl: "./audio/npc/StopSkipped/stop%20right%20here.ogg", },
  { id: "npc-StopSkipped-6", category: "StopSkipped", number: 6, title: { zh: "why did u do this to me", en: "why did u do this to me" }, detail: { zh: "跳站", en: "Stop skipped" }, audioUrl: "./audio/npc/StopSkipped/why%20did%20u%20do%20this%20to%20me.ogg", },
  { id: "npc-StopSkipped-7", category: "StopSkipped", number: 7, title: { zh: "you just miss my stop", en: "you just miss my stop" }, detail: { zh: "跳站", en: "Stop skipped" }, audioUrl: "./audio/npc/StopSkipped/you%20just%20miss%20my%20stop.ogg", },
  { id: "npc-Wrong-1", category: "Wrong", number: 1, title: { zh: "Donald Trump   Wrong Sound Effect", en: "Donald Trump   Wrong Sound Effect" }, detail: { zh: "乘错车", en: "Wrong route" }, audioUrl: "./audio/npc/Wrong/Donald%20Trump%20-%20Wrong%20Sound%20Effect.ogg", },
  { id: "npc-Wrong-2", category: "Wrong", number: 2, title: { zh: "i am reporting you", en: "i am reporting you" }, detail: { zh: "乘错车", en: "Wrong route" }, audioUrl: "./audio/npc/Wrong/i%20am%20reporting%20you.ogg", },
  { id: "npc-Wrong-3", category: "Wrong", number: 3, title: { zh: "oh my god", en: "oh my god" }, detail: { zh: "乘错车", en: "Wrong route" }, audioUrl: "./audio/npc/Wrong/oh%20my%20god.ogg", },
  { id: "npc-Wrong-4", category: "Wrong", number: 4, title: { zh: "Oh No", en: "Oh No" }, detail: { zh: "乘错车", en: "Wrong route" }, audioUrl: "./audio/npc/Wrong/Oh%20No.ogg", },
  { id: "npc-FareWrong-1", category: "FareWrong", number: 1, title: { zh: "aww", en: "aww" }, detail: { zh: "车费错误", en: "Wrong fare" }, audioUrl: "./audio/npc/FareWrong/aww.ogg", },
  { id: "npc-FareWrong-2", category: "FareWrong", number: 2, title: { zh: "Donald Trump   Wrong Sound Effect", en: "Donald Trump   Wrong Sound Effect" }, detail: { zh: "车费错误", en: "Wrong fare" }, audioUrl: "./audio/npc/FareWrong/Donald%20Trump%20-%20Wrong%20Sound%20Effect.ogg", },
  { id: "npc-FareWrong-3", category: "FareWrong", number: 3, title: { zh: "i am reporting you", en: "i am reporting you" }, detail: { zh: "车费错误", en: "Wrong fare" }, audioUrl: "./audio/npc/FareWrong/i%20am%20reporting%20you.ogg", },
  { id: "npc-DoorOpened-1", category: "DoorOpened", number: 1, title: { zh: "i am reporting you", en: "i am reporting you" }, detail: { zh: "车门打开", en: "Door opened" }, audioUrl: "./audio/npc/DoorOpened/i%20am%20reporting%20you.ogg", },
  { id: "npc-DoorOpened-2", category: "DoorOpened", number: 2, title: { zh: "oh my god", en: "oh my god" }, detail: { zh: "车门打开", en: "Door opened" }, audioUrl: "./audio/npc/DoorOpened/oh%20my%20god.ogg", },
  { id: "npc-DoorOpened-3", category: "DoorOpened", number: 3, title: { zh: "stop right here", en: "stop right here" }, detail: { zh: "车门打开", en: "Door opened" }, audioUrl: "./audio/npc/DoorOpened/stop%20right%20here.ogg", },
  { id: "npc-DoorOpened-4", category: "DoorOpened", number: 4, title: { zh: "why did u do this to me", en: "why did u do this to me" }, detail: { zh: "车门打开", en: "Door opened" }, audioUrl: "./audio/npc/DoorOpened/why%20did%20u%20do%20this%20to%20me.ogg", },
  { id: "npc-DoorClosed-placeholder", category: "DoorClosed", number: 1, title: { zh: "车门关闭（待补充）", en: "Door closed (pending)" }, detail: { zh: "车门关闭", en: "Door closed" }, audioUrl: null, unavailable: true, },
  { id: "npc-Camera-1", category: "Camera", number: 1, title: { zh: "35 Mm Nikon F3 Camera 2 (SFX)", en: "35 Mm Nikon F3 Camera 2 (SFX)" }, detail: { zh: "相机", en: "Camera" }, audioUrl: "./audio/npc/Camera/35%20Mm%20Nikon%20F3%20Camera%202%20(SFX).ogg", },
  { id: "npc-Camera-2", category: "Camera", number: 2, title: { zh: "Camera Surreal 35 Mm Shutter 2 (SFX)", en: "Camera Surreal 35 Mm Shutter 2 (SFX)" }, detail: { zh: "相机", en: "Camera" }, audioUrl: "./audio/npc/Camera/Camera%20Surreal%2035%20Mm%20Shutter%202%20(SFX).ogg", },
  { id: "npc-Cold-placeholder", category: "Cold", number: 1, title: { zh: "寒冷（待补充）", en: "Cold (pending)" }, detail: { zh: "寒冷", en: "Cold" }, audioUrl: null, unavailable: true, },
  { id: "npc-Hot-placeholder", category: "Hot", number: 1, title: { zh: "炎热（待补充）", en: "Hot (pending)" }, detail: { zh: "炎热", en: "Hot" }, audioUrl: null, unavailable: true, },
  { id: "npc-NoKneel-placeholder", category: "NoKneel", number: 1, title: { zh: "请勿跪坐（待补充）", en: "No kneeling (pending)" }, detail: { zh: "请勿跪坐", en: "No kneeling" }, audioUrl: null, unavailable: true, },
]
