/** Generated by scripts/sync-roblox-images.mjs — do not edit manually. */
export const ROBLOX_HEADSHOT_FILES: Record<number, string> = {
  22827563: 'roblox-headshots/22827563.png',
  23651717: 'roblox-headshots/23651717.png',
  45031838: 'roblox-headshots/45031838.png',
  49963087: 'roblox-headshots/49963087.png',
  62628442: 'roblox-headshots/62628442.png',
  64664624: 'roblox-headshots/64664624.png',
  66366295: 'roblox-headshots/66366295.png',
  75537160: 'roblox-headshots/75537160.png',
  167309348: 'roblox-headshots/167309348.png',
  198263866: 'roblox-headshots/198263866.png',
  228401896: 'roblox-headshots/228401896.png',
  469478817: 'roblox-headshots/469478817.png',
  658480530: 'roblox-headshots/658480530.png',
  907362880: 'roblox-headshots/907362880.png',
  1201592636: 'roblox-headshots/1201592636.png',
  1407018660: 'roblox-headshots/1407018660.png',
  1467395817: 'roblox-headshots/1467395817.png',
  1478213043: 'roblox-headshots/1478213043.png',
  1964930886: 'roblox-headshots/1964930886.png',
  2024891839: 'roblox-headshots/2024891839.png',
  2349382521: 'roblox-headshots/2349382521.png',
  2419957129: 'roblox-headshots/2419957129.png',
  3895858825: 'roblox-headshots/3895858825.png',
  4044819590: 'roblox-headshots/4044819590.png',
}

export const REAL_SHOP_IMAGE_FILES = {
  passVip: 'real-shop/5903903949.png',
  passDeveloper: 'real-shop/16337655177.png',
  passUltimate: 'real-shop/16337461722.png',
  passMaster: 'real-shop/15681733281.png',
  uiClose: 'real-shop/6031094678.png',
  uiGift: 'real-shop/6023426978.png',
} as const

export const REAL_PROFILE_IMAGE_FILES = {
  chalkboard: 'real-profile/9140355801.png',
} as const
