/** Generated by scripts/build-route-n171-audio-manifest.mjs — do not edit by hand. */

import { routes } from './routes'
import type { RouteStopAudioAtRow } from './routeStopAudio21A'

export const ROUTE_N171_ID = "N171"
export const ROUTE_N171_AUDIO_DIR = './audio/routes/N171'
export const ROUTE_N171_AT_PREFIX = "n171"

const ROUTE_N171_AT_STOP_INDICES: Readonly<Record<number, readonly number[]>> = {
  0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59] as const,
  1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 27, 28, 30, 31, 32, 33, 34, 35, 37, 39, 40, 41, 42, 43, 44, 46, 48, 49, 51, 52, 56, 58, 59, 60, 61] as const,
}

function audioUrlForAtStop(directionGroupIndex: number, atStopIndex: number): string {
  const dirKey = directionGroupIndex === 0 ? 'n' : 's'
  return `${ROUTE_N171_AUDIO_DIR}/${ROUTE_N171_AT_PREFIX}-${dirKey}-at-${String(atStopIndex).padStart(2, '0')}.mp3`
}

export function getRouteN171StopAudioByAtIndex(
  directionGroupIndex: number,
): Map<number, RouteStopAudioAtRow> | null {
  const route = routes.find((r) => r.id === ROUTE_N171_ID)
  const stopList = route?.stops?.[directionGroupIndex]?.list
  const indices = ROUTE_N171_AT_STOP_INDICES[directionGroupIndex]
  if (!stopList?.length || !indices?.length) return null

  const map = new Map<number, RouteStopAudioAtRow>()

  for (const at of indices) {
    const next = stopList[at + 1]
    const label = next?.name
    if (!label) continue
    map.set(at, {
      atStopIndex: at,
      nextStopLabel: label,
      audioUrl: audioUrlForAtStop(directionGroupIndex, at),
    })
  }

  return map.size > 0 ? map : null
}
