/** Generated by scripts/build-route-direction-audio-manifest.mjs — do not edit by hand. */

import { routes } from './routes'
import type { RouteStopAudioAtRow } from './routeStopAudio21A'
import { routeAudioFilePrefix } from '../utils/routeAudioFilePrefix'

export const ROUTE_DIRECTION_AUDIO_ROUTE_IDS = ["N171"] as const

const ROUTE_DIRECTION_AT_STOP_INDICES: Readonly<
  Record<string, Readonly<Record<number, readonly number[]>>>
> = {
  "N171": {
    0: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59] as const,
    1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 26, 27, 29, 30, 31, 32, 33, 34, 36, 38, 39, 40, 41, 42, 43, 45, 47, 48, 50, 51, 55, 57, 58, 59, 60, 61] as const,
  },
}

function audioUrlForAtStop(routeId: string, directionGroupIndex: number, atStopIndex: number): string {
  const group = routes.find((route) => route.id === routeId)?.stops?.[directionGroupIndex]
  const dirKey = (group?.directionKey ?? (directionGroupIndex === 0 ? 'N' : 'S')).toLowerCase()
  const prefix = routeAudioFilePrefix(routeId)
  return `./audio/routes/${routeId}/${prefix}-${dirKey}-at-${String(atStopIndex).padStart(2, '0')}.mp3`
}

export function getRouteDirectionStopAudioByAtIndex(
  routeId: string,
  directionGroupIndex: number,
): Map<number, RouteStopAudioAtRow> | null {
  const indices = ROUTE_DIRECTION_AT_STOP_INDICES[routeId]?.[directionGroupIndex]
  const stopList = routes.find((route) => route.id === routeId)?.stops?.[directionGroupIndex]?.list
  if (!indices?.length || !stopList?.length) return null

  const map = new Map<number, RouteStopAudioAtRow>()
  for (const at of indices) {
    const next = stopList[at + 1]
    const label = next?.name
    if (!label) continue
    map.set(at, {
      atStopIndex: at,
      nextStopLabel: label,
      audioUrl: audioUrlForAtStop(routeId, directionGroupIndex, at),
    })
  }
  return map.size > 0 ? map : null
}
