/** Generated by scripts/build-route-maps-manifest.mjs — do not edit by hand. */

export const ROUTE_MAP_CANONICAL_IDS = ["77X","21"] as const

export const ROUTE_MAP_ROUTE_ALIASES: Record<string, string> = {
  '77XA': '77X',
  '21A': '21',
}

export type RouteMapViewKind = 'path' | 'height'

export const ROUTE_MAPS_BY_CANONICAL_ID: Record<string, readonly RouteMapViewKind[]> = {
  '21': ['path'],
  '77X': ['path'],
}

export function resolveRouteMapRouteId(routeId: string): string | null {
  const canonical = ROUTE_MAP_ROUTE_ALIASES[routeId] ?? routeId
  return Object.prototype.hasOwnProperty.call(ROUTE_MAPS_BY_CANONICAL_ID, canonical) ? canonical : null
}

export function listRouteMapKinds(routeId: string): RouteMapViewKind[] {
  const canonical = resolveRouteMapRouteId(routeId)
  if (!canonical) return []
  return [...(ROUTE_MAPS_BY_CANONICAL_ID[canonical] ?? [])]
}
