/** Generated by scripts/build-stop-name-audio-manifest.mjs — do not edit by hand. */

import type { BilingualText } from '../types/route'
import { STOP_NAME_ALIASES } from '../utils/stopNameAudioMatch'

export const STOP_NAME_AUDIO_URL_PREFIX = "./audio/routes/stop-names"

export interface StopNameAudioManifestEntry {
  file: string
  hint: string
  passSuffix: number | null
  kind: 'stop' | 'alight'
}

export const STOP_NAME_AUDIO_MANIFEST: readonly StopNameAudioManifestEntry[] = [
  { file: "21路艾迪城.mp3", hint: "艾迪城", passSuffix: null, kind: "stop" },
  { file: "21路艾迪路.mp3", hint: "艾迪路", passSuffix: null, kind: "stop" },
  { file: "21路白鸽邨.mp3", hint: "白鸽邨", passSuffix: null, kind: "stop" },
  { file: "21路白鸽山1.mp3", hint: "白鸽山", passSuffix: 1, kind: "stop" },
  { file: "21路白鸽山2.mp3", hint: "白鸽山", passSuffix: 2, kind: "stop" },
  { file: "21路白鸽消防局1.mp3", hint: "白鸽消防局", passSuffix: 1, kind: "stop" },
  { file: "21路赖德里1.mp3", hint: "赖德里", passSuffix: 1, kind: "stop" },
  { file: "21路赖德商场1.mp3", hint: "赖德商场", passSuffix: 1, kind: "stop" },
  { file: "21路篮球场1.mp3", hint: "篮球场", passSuffix: 1, kind: "stop" },
  { file: "21路三哥大厦1.mp3", hint: "三哥大厦", passSuffix: 1, kind: "stop" },
  { file: "21路时间廊1.mp3", hint: "时间廊", passSuffix: 1, kind: "stop" },
  { file: "21路西区医院1.mp3", hint: "西区医院", passSuffix: 1, kind: "stop" },
  { file: "21路伊迪城1.mp3", hint: "伊迪城", passSuffix: 1, kind: "stop" },
  { file: "21路银行大厦1.mp3", hint: "银行大厦", passSuffix: 1, kind: "stop" },
  { file: "21路RBX TV.mp3", hint: "RBX TV", passSuffix: null, kind: "stop" },
  { file: "21路RBXHQ1.mp3", hint: "RBXHQ", passSuffix: 1, kind: "stop" },
]

function stopNameMatchesHint(stopName: BilingualText, hint: string): boolean {
  const zh = stopName.zh?.trim() ?? ''
  const en = stopName.en?.trim() ?? ''
  const normalizedHint = hint.trim()
  if (!normalizedHint) return false

  if (zh && (zh === normalizedHint || zh.includes(normalizedHint) || normalizedHint.includes(zh))) {
    return true
  }

  if (en && (en === normalizedHint || en.includes(normalizedHint) || normalizedHint.includes(en))) {
    return true
  }

  const aliases = STOP_NAME_ALIASES[en] ?? []
  return aliases.some(
    (alias) =>
      alias === normalizedHint ||
      alias.includes(normalizedHint) ||
      normalizedHint.includes(alias),
  )
}

export function passIndexForNextStop(
  stopList: { name: BilingualText }[],
  nextIndex: number,
): number {
  const next = stopList[nextIndex]
  if (!next) return 0
  const nextZh = next.name.zh
  const nextEn = next.name.en
  let pass = 0
  for (let i = 0; i < nextIndex; i++) {
    const s = stopList[i]
    if (nextZh && s.name.zh === nextZh) pass++
    else if (nextEn && s.name.en === nextEn) pass++
  }
  return pass
}

function encodeAudioFilename(filename: string): string {
  return [...filename]
    .map((ch) => (/[A-Za-z0-9._-]/.test(ch) ? ch : encodeURIComponent(ch)))
    .join('')
}

export function findStopNameAudio(
  nextStop: BilingualText,
  passIndex: number,
): { audioUrl: string; sourceFile: string } | undefined {
  const candidates = STOP_NAME_AUDIO_MANIFEST.filter(
    (entry) => entry.kind === 'stop' && stopNameMatchesHint(nextStop, entry.hint),
  )
  if (candidates.length === 0) return undefined

  const desiredPass = passIndex + 1
  const exactPass = candidates.find((c) => c.passSuffix === desiredPass)
  const chosen =
    exactPass ??
    candidates.find((c) => c.passSuffix == null) ??
    (candidates.length === 1 ? candidates[0] : candidates.find((c) => c.passSuffix === 1)) ??
    candidates[0]

  if (!chosen) return undefined

  return {
    sourceFile: chosen.file,
    audioUrl: `${STOP_NAME_AUDIO_URL_PREFIX}/${encodeAudioFilename(chosen.file)}`,
  }
}
