/** Generated by scripts/build-world-map-routes-manifest.mjs — do not edit by hand. */

export type WorldMapPoint = readonly [number, number]

export interface WorldMapRouteDirection {
  directionIndex: number
  points: readonly WorldMapPoint[]
}

export interface WorldMapRoutePaths {
  directions: readonly WorldMapRouteDirection[]
}

export const WORLD_MAP_ROUTE_ALIASES: Record<string, string> = {
  '21A': '21',
}

export const WORLD_MAP_ROUTE_PATHS: Record<string, WorldMapRoutePaths> = {
  '21': {
    "directions": [
      {
        "directionIndex": 0,
        "points": [
          [
            0.118,
            0.902
          ],
          [
            0.105,
            0.885
          ],
          [
            0.108,
            0.868
          ],
          [
            0.125,
            0.855
          ],
          [
            0.145,
            0.848
          ],
          [
            0.158,
            0.835
          ],
          [
            0.152,
            0.82
          ],
          [
            0.138,
            0.808
          ],
          [
            0.142,
            0.792
          ],
          [
            0.158,
            0.785
          ],
          [
            0.172,
            0.792
          ],
          [
            0.185,
            0.805
          ],
          [
            0.188,
            0.818
          ],
          [
            0.21,
            0.825
          ],
          [
            0.245,
            0.818
          ],
          [
            0.258,
            0.835
          ],
          [
            0.248,
            0.852
          ],
          [
            0.228,
            0.845
          ],
          [
            0.195,
            0.858
          ],
          [
            0.178,
            0.872
          ],
          [
            0.165,
            0.885
          ],
          [
            0.148,
            0.895
          ],
          [
            0.13,
            0.9
          ],
          [
            0.118,
            0.902
          ]
        ]
      }
    ]
  },
}
